[ADD] website slides module courtesy: Mantavya Gajjar(mga-odoo), Ravi Gadhia(rga-odoo), Vijay Patel(vip-odoo), Pariket Trivedi(ptr-odoo)
[FIX] broken view xml

[REF]: refactor clides to adapt channel concept

[IMP]: implement like button

[IMP]: add like button on slide detail view

[IMP]: different aspect ratio for slide and video

[IMP]: improve channel landine page

[IMP] imporve like/dislike feature on slideview

[IMP]: implement channel gridview

[IMP] small layout improvement

[IMP]: improve subscrive view on channel page

[IMP]: small improvement, added back button beside titles
[IMP]: small improvements based on the review
[FIX]: small fix for creating slide
[FIX]: small improvements based on the review

[IMP]: implement channel promote method for channel

[IMP]: fix based on the review

[IMP]: implement channel notification for new slide published

[FIX] fix view for types and sorting

[FIX]: fix filters and sorting

[FIX]: fix filters and sorting

[FIX]: fix filters and sorting

[FIX]: fix filters and sorting

[FIX]: small fix

[FIX]: fix filters and sorting

[FIX] like/dislike + invalid url redirect

[imp] website_slides: implimented pdfview

[FIX/IMP] Add slide dialog box should display progress when fetching data + fix page title of detail slide view

[IMP]: implement url based on the content types and tags

[IMP]: implement url based on the content types and tags

[IMP]: implement url based on the content types and tags

[FIX]: small for broken url when adding new slides

[IMP]: small fix for url based on the content types and tags

[FIX]: change icon for the pdf viewer

[FIX]: fix url when sending in email

[FIX]: small view fix

[FIX]: small view fix

[FIX]: small view fix

[FIX]: fix some small issues based on review

[FIX]: fix some small issues based on review

[FIX]: fix some small issues based on review

[FIX]: fix some small issues based on review

[FIX]: fix some small issues based on review

[imp] website_slides: optimized performance of pdf viwer

[FIX]: fix some small issues based on review

[FIX]: fix some small issues based on review

[FIX]: fix some small issues based on review

[FIX]: fix some small issues based on review

[IMP] [website_slides] fatched youtube thumbnail image and video description

[FIX]: fix some small issues based on review

[FIX]: fix some small issues based on review

[FIX]: fix some small issues based on review

[FIX]: fix some small issues based on review

[IMP] use tabs for filter

[IMP]: improve design for channel page

[IMP]: improve design for channel page

[IMP]: improve design for channel page

[IMP]: improve design for channel page

[FIX]: fix issues related to view padding on main page

[IMP] post height width of canvase to server

[IMP]: implement main page to group content

[imp] website_slides: implimented keyboard navigation in pdfviewer

[IMP]: implement sorting menu

[FIX] fix small issue

[FIX] fix small issue

[FIX] fix small issue

[FIX] fix header to make it different

[FIX] fix header to make it different

[FIX] small fix to get correct page when only one channel available

[FIX] small fix for search result display

[FIX] small fix for search result display

[FIX] small fix for search

[FIX]: fix an issue for the image height and width

[imp] website_slides: implimented new design and share option on top in pdfviewer

[FIX]: fix an issue for the image height and width

[imp] website_slides: optimized fullscreen view in pdfview

[IMP] Upload dialog box for public user

[FIX]: implement model based methods to get url and embade code

[FIX]: fix location of upload button

[IMP]: implement infographics

[IMP]: fix small issue related to height

[IMP] allow images upload

[imp] website_slides: optimized share functionality and design in pdfview

[FIX]: small fix

[FIX]: fix links to section

[IMP] Presenation should be upload to current open channel

[imp] website_slides: implimented loader on pdf load in pdf view and optimized infographic view

[IMP] remove new slides dialog from website editor pannel

[IMP]: big message to ask for upload a first message

[FIX]: fix main page header for mobile view

[IMP]: fix small issue for navigation

[IMP]: fix small issue for total count on pager

[FIX]: fix small issue to get thumb image

[imp] website_slides: implimented dynamic tab switching when no content in discuss tab in slide detail view

[imp] website_slides: implimented dynamic text change when slecting dropdown filter on right side in slide gridview

[fix] website_slides: fix like and dislike functionality in slide detail view

[imp] website_slides: optimized like and dislike functionality in slide detail view

[imp] website_slides: optimized share template in pdfview

[IMP] PDFViewer widget

[FIX]: fix a small probelm for list of relted slides

[imp] website_slides: added cookie functionality for like and unlike once in slide detail view

[imp] website_slides: optimized nevigation in pdfview

[imp] website_slides: implimented fullscreen in pdfview

[imp] website_slides: optimized design of pdfview

[imp] website_slides: optimized share tab in pdfview

[imp] website_slides: like dislike cookies functionality implimented in slide detail view

[IMP] fullscreen

[imp] website_slides: optimize code of slides js

[IMP]: improve share tab

[IMP] upload dialog should not display on redirect login

[imp] website_slides: implimented cookies in like unlike buttons in slide detail view

[imp] website_slides: optimized like deslike code for localstorage in slide detail view

[IMP] Upload Dialog: display preview of content and set name as content title/filename

[FIX]: fix image on upload dialoug

[IMP] use google API V3 for fetch image and title

[IMP] fetch index content from pdfjs

[ADD] website_slides: added demo data and related files(PNG images for infographic and PDFs for presentations and document)

[IMP]: demo data for infographic and add parent menuitem.

[IMP]: add demo data for category.

[IMP]: fix small issue for total count on pager

[IMP] improve view for share and embade code

[FIX]: small fix for new api

[imp] website_slides: implimented alert message in like unlike functionality in slide detailview

[FIX] website_mail: after subscription dislay success alert message

[IMP] Crawler test case: escape white space like unsafe charater and convert it to real url quote

[IMP]: add images

[REBASE]: rebase of module developed by rga@openerp.com, vip@openerp.com, ptr@openerp.com, ara@openerp.com and mga@openerp.com

[IMP] PDFView: loading indicator display on when file is not loaded and click on navigation button

[FIX]: add new date_publish to maintain sorting for newest correctly instead of using write_date

[FIX]: fix iaaues may occured for loading the js and issue related to the upload and access rights

[IMP]: refactor model, controller and template. remove ir.attachment and create a new model slide.slide

[CLEAN]: remove unused variables and change attachment => slide

[FIX] fetch pdf datas only when slide-id found

[IMP]: improve code for to get youtube data

[imp] website_slides: converted extract_youtube_id function to regular expression for get youtube id

[imp] website_slides: Re-converted extract_youtube_id function to regular expression for get youtube id

[IMP]: improve code for model, view and controller

[IMP] add quick propt dialog to create new channel and category

[FIX] FF specific ui issue: send by mail button should be visible in full width

[FIX] broken assets

[FIX]: improve data and demo data

[IMP/ADD] minified build of pdf.js and pdf.worker.js, used closure compiler to generate minifield build, ref: https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#minified

[imp] website_slides: optimized pdf viewer in embed view after backend corrections

[FIX] Crawler should handle white space in path as like browser does

[IMP] improve backend views

[IMP] Apply PEP8

[imp] website_slides: added promote functionality for slides in slide grid view

[IMP] usability: backend view + add channel setting button in frontend

[IMP]: improve promote button in slide-grid layout

[IMP] Set page titel for channels and set required field based on slide type

[IMP]: small type improvements

[imp] website_slides: optimize image height problem in related slides list in embed view

[IMP/ADD] slide download option

[FIX] render_attribute should return utf-8 encoded string
    openerp/addons/base/ir/ir_qweb.py", line 282, in render_node
        generated_attributes += self.render_attribute(element, att, val, qwebcontext)
        QWebException: 'ascii' codec can't decode byte 0xc3 in position 29: ordinal not in range(128)
    exception when try to concate utf-8 encoded string(generated_attributes) to unicode

[IMP] slide download redirect and authentication + setting and add category button should dislpay only in chanage view

[IMP]: improve code and typo based on review

[IMP] remove textext dependecy use bootstrap select2 for tag selection

[IMP] Upload Dialog: support google drive document

[IMP]: implement google doc import to slides

[IMP] backend: onchange of document url get required field using api and set it

[IMP] frontend view + youtube or google doc url should be work with dialog box

[IMP] remvoe dual logic for fetch data from external url, now server is responsible to get currect data and client is dumb as always

[IMP] set default width and height for shere Embed iframe

[IMP]: improve code for Category view and email template for notification emails

[IMP]: improve view for /channel

[IMP] display loading status on dialog when fetching data from server

[IMP] usability as per review

[REM/IMP] small usability improvement + remove catogory dialog box from website editorbar

[IMP] Upload dialog data validation

[IMP] add user group on upload button

[IMP] only one message post, if presentation not publish yet then message for review and it publish then message for new presentation upload

[REM] It's seems mail subscription has been fixed in master so ugly fix

[IMP] Display uncategorized presentation at home

[REF] code refactor + improve help + fix typo

[IMP] set wrapper of API + refactor code

[IMP] set image_thumb and image_medium as compute field and eval it's value from high resolution image binary field data

[IMP] view count should not be increase on refresh + fix typo

[IMP] Channel category should be create frontend dialog box. impement select2 to wrapper to optimize code

[IMP] presentation should not be like and unlink by same user + set file upload limit

[IMP] at least one channel should published so public user can see it + fix mouse hove link on tags

[IMP] Fix timeago issue: dispaly currect time as timeago if persentation one week old else display formated date string

[IMP] Upgrade select2-bootstrap.css to make it compatible with web/static/lib/select2/select2.js

[ADD] access rights

[IMP] message if not channale created or published.

[IMP] minor usability improvement + error handling for password protected pdf file upload

[IMP] better ui

[IMP] backend view url

[IMP] better view

[IMP] design

[IMP] email template

[IMP] give upload access only if user have channel access first

[IMP] usability and fix typo

[ADD] tooltips

[IMP] update license and file upload limit

[IMP] right align view count

[IMP] dont show text if no right to upload

[FIX] sendmail broken image: gmail only fetch image src with absolute path

[IMP] remove abs url

[IMP] put back fix

[IMP] Add the charset and order imports

[IMP] broke long line for batter code readability follow pep-8 except E128,E501

[IMP] model_obj ==> Model

[IMP] change route tags ==> tag, types ==> slide_type

[IMP] rename errormessage==> access_error_msg, sendemail==>send_share_email

[IMP] route for link/dislikes

[IMP] store function field and lazy=False for group_read fetch

[IMP] access rules

[FIX] line break sucks arithmetic operations

[IMP] refactor routes

[IMP] Slide Access configuration

[IMP] move crope image to tools/image.py

[FIX] broken by route change

[IMP] add doc string for model

[MOV] view count logic from model to controller

[IMP] share_url set as model field

[REM] get_thumb_url

[FIX] access right for portal user

[IMP] remove sudo

[IMP] remove useless api decorator

[REM] dead code

[IMP] split embed view controller and xml view

[IMP] remove @api.multi from onchange, make every one happy:)

[IMP] change licence and improve doc string

[IMP] refactore check_unique_slide method

[MOV] Prepare create values logic from controller to model

[FIX] security access for various visibility configuration of channel

Do not publish slide on direct upload if user has not publisher rights

[IMP] remove select2-bootstrap-css upgradation, made separate branch for the same

[IMP] remove try catch handle it using access rights, broke too long html line

[REM] test_crawl fix, make separate branch for the same

[REM] qweb fix, make separate branch for the same